[db_settings]
data_folder = "./data"
migrations_folder = "./crates/server/migrations"

[api_settings]
domain = "127.0.0.1"
port = "8900"
private_key_file = "./creds/private.key"

[ui_settings]
remote_url = "http://127.0.0.1:8900"
ui_dir = "./crates/public_ui"
